import { StyleSheet } from "react-native";

const colors = {
  white: "#FFF",
  subtitle: "#F2F2F2",
  loginColor: "#FEFEFE",
  primary: "#FFC700",
  secondary: "#6C6C6C",
  backgroundColor: "#525252",
  black: "#000",
  detailsText: "#9E9E9E",
  arrow: "#937d1c",
  subTitleDetail: "#CDCDCD",
};

const text = StyleSheet.create({
  bold: {
    fontWeight: "bold",
    fontSize: 26,
    lineHeight: 35,
    textAlign: "center",
    letterSpacing: -0.2,
    color: colors.white,
    marginBottom: 50,
  },
  regular: {
    fontSize: 16,
    fontWeight: "normal",
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: -0.2,
    color: colors.subtitle,
  },
  primaryText: {
    textTransform: "uppercase",
    fontWeight: "bold",
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: -0.2,
    alignItems: "center",
    paddingHorizontal: "24%",
  },
  title: {
    marginLeft: 15,
    marginTop: 20,
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 18,
    lineHeight: 25,
    letterSpacing: -0.2,
    color: colors.white,
  },
  year: {
    marginLeft: 15,
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.2,
    color: colors.primary,
  },
  subTitle: {
    marginLeft: 15,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.2,
    color: colors.subTitleDetail,
  },
  forDetailsText: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 14,
    lineHeight: 19,
    textAlign: "center",
    letterSpacing: -0.2,
    textTransform: "uppercase",
    color: colors.white,
  },
});

const theme = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  card: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.backgroundColor,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  mainImage: {
    width: 340,
    height: 252,
  },
  textContainer: {
    paddingHorizontal: 80,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    width: "80%",
    height: 50,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 10,
  },
  arrowContainer: {
    width: 50,
    height: 50,
    backgroundColor: colors.arrow,
    flexDirection: "row",
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContainer: {
    padding: 10,
    backgroundColor: colors.backgroundColor,
  },
  movieCard: {
    width: "95%",
    backgroundColor: colors.secondary,
    marginTop: 18,
    paddingTop: 18,
    paddingBottom: 20,
    marginHorizontal: "2%",
    borderRadius: 10,
  },
  buttonForDetails: {
    border: "1px solid #E1E1E1",
    borderRadius: 10,
    width: "90%",
    marginLeft: 15,
    padding: 10,
    alignItems: "center",
    marginTop: 10,
  },
});

export { colors, theme, text };
